version: '3.9'
services:
  # database section
    identitydb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: identitydb
        environment:
            SA_PASSWORD: "Passw0rd!"
            ACCEPT_EULA: "Y"
        volumes:
            - identity_sqlserver_data:/var/opt/mssql
        restart: always
        ports:
            - "1436:1433"

  # api section
    identity.api:
        image: ${DOCKER_REGISTRY-}identity-api:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: .
            dockerfile: Microservices.IDP/Dockerfile
        container_name: identity.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - "ConnectionStrings:IdentitySqlConnection=Server=identitydb;Database=Identity;User Id=sa;Password=Passw0rd!;Multipleactiveresultsets=true"
            - "IdentityServer:BaseUrl=http://localhost:6001"
            - "IdentityServer:IssuerUri=http://localhost:6001"
        depends_on: 
            - identitydb
        ports:
            - "6001:80"
        restart: always
        
networks:
  default:
    name: netcore_microservices
    external: true

volumes:
  identity_sqlserver_data:
    external: false
    